[project]
name = "lab-data-warehouse-group-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-snowflake>=1.12.1",
    "dlt[parquet,snowflake]>=1.31.0",
    "dotenv>=0.9.9",
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "snowflake-connector-python>=4.8.0",
    "streamlit>=1.65.0",
]
