USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS "FLIGHTDATA_WH"
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for flight data analysis';

