USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS FLIGHTDATA_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FLIGHTDATA_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS FLIGHTDATA_DB.MARTS;

USE ROLE SECURITYADMIN;

--funktionella roller som har en uppgift i pipelinen
CREATE ROLE IF NOT EXISTS LOADER; --DLT
CREATE ROLE IF NOT EXISTS TRANSFORMER; --DBT
CREATE ROLE IF NOT EXISTS REPORTER; --DASHBOARD

--roll för oss om något behöver göras manuellt i Snowflake, ärver bara från de andra rollerna
CREATE ROLE IF NOT EXISTS ENGINEER;

-- Loader rättigheter
GRANT USAGE ON WAREHOUSE FLIGHTDATA_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE FLIGHTDATA_DB TO ROLE LOADER;
GRANT ALL PRIVILEGES ON SCHEMA FLIGHTDATA_DB.RAW TO ROLE LOADER; -- får bara rättigheter till raw för att kunna ladda in

-- Transformer rättigheter
GRANT USAGE ON WAREHOUSE FLIGHTDATA_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE FLIGHTDATA_DB TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA FLIGHTDATA_DB.RAW TO ROLE TRANSFORMER; 
GRANT SELECT ON ALL TABLES IN SCHEMA FLIGHTDATA_DB.RAW TO ROLE TRANSFORMER; -- får bara rättigheter till raw för att kunna läsa in
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHTDATA_DB.RAW TO ROLE TRANSFORMER; --ska kunna läsa in från raw på allt som skapas i framtiden
GRANT ALL PRIVILEGES ON SCHEMA FLIGHTDATA_DB.STAGING TO ROLE TRANSFORMER; --Ska kunna ändra i staging för att kunna transformera
GRANT ALL PRIVILEGES ON SCHEMA FLIGHTDATA_DB.MARTS TO ROLE TRANSFORMER; --ska kunna ändra i marts för att kunna transformera

-- reporter rättigheter
GRANT USAGE ON WAREHOUSE FLIGHTDATA_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE FLIGHTDATA_DB TO ROLE REPORTER;
GRANT USAGE ON SCHEMA FLIGHTDATA_DB.MARTS TO ROLE REPORTER; --ska bara kunna läsa in från marts för att kunna skapa rapporter
GRANT SELECT ON ALL TABLES IN SCHEMA FLIGHTDATA_DB.MARTS TO ROLE REPORTER; --ska kunna läsa in från marts på allt som skapas i framtiden
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLIGHTDATA_DB.MARTS TO ROLE REPORTER; --ska kunna läsa in från marts på allt som skapas i framtiden
GRANT SELECT ON ALL VIEWS IN SCHEMA FLIGHTDATA_DB.MARTS TO ROLE REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FLIGHTDATA_DB.MARTS TO ROLE REPORTER;

-- rollhierarki
GRANT ROLE LOADER TO ROLE ENGINEER;
GRANT ROLE TRANSFORMER TO ROLE ENGINEER;
GRANT ROLE REPORTER TO ROLE ENGINEER;